//
//  ScanHistoryStyleSheet.js
//  ScanRelatedScreens
//
//  Created by Supernova.
//  Copyright © 2018 Supernova. All rights reserved.
//

import { StyleSheet } from "react-native"

const styles = StyleSheet.create({
	profileView: {
		backgroundColor: "rgb(244, 242, 244)",
		flex: 1,
	},
	viewView: {
		backgroundColor: "transparent",
		flex: 1,
	},
	wholeviewView: {
		backgroundColor: "white",
		position: "absolute",
		left: 0,
		right: 0,
		top: 4,
		height: 667,
	},
	viewNineView: {
		backgroundColor: "transparent",
		height: 62,
	},
	headerView: {
		backgroundColor: "rgba(27, 67, 147, 0.92)",
		position: "absolute",
		left: 0,
		right: 0,
		top: 0,
		bottom: 0,
	},
	imageTwelveImage: {
		backgroundColor: "transparent",
		resizeMode: "center",
		width: 26,
		height: 33,
	},
	labelElevenText: {
		backgroundColor: "transparent",
		color: "white",
		//fontFamily: "Roboto-Regular",
		fontSize: 17,
		fontStyle: "normal",
		fontWeight: "normal",
		textAlign: "left",
		marginLeft: 36,
		marginTop: 4,
	},
	imageElevenImage: {
		backgroundColor: "transparent",
		resizeMode: "center",
		flex: 1,
		height: 33,
		marginLeft: 159,
	},
	viewTwoView: {
		backgroundColor: "transparent",
		height: 605,
	},
	bodyView: {
		backgroundColor: "white",
		position: "absolute",
		left: 0,
		right: 0,
		top: 0,
		height: 605,
	},
	viewThreeView: {
		backgroundColor: "transparent",
		height: 455,
	},
	scanninginfoView: {
		backgroundColor: "white",
		position: "absolute",
		left: 0,
		width: 375,
		top: 0,
		height: 548,
	},
	viewEightView: {
		backgroundColor: "transparent",
		height: 72,
		marginLeft: 4,
	},
	game1View: {
		backgroundColor: "white",
		position: "absolute",
		left: 0,
		width: 375,
		top: 0,
		height: 78,
	},
	imageTenImage: {
		backgroundColor: "transparent",
		resizeMode: "center",
		width: 63,
		height: 59,
	},
	labelTenText: {
		backgroundColor: "transparent",
		color: "rgba(0, 0, 0, 0.8)",
		//fontFamily: "Roboto-Regular",
		fontSize: 17,
		fontStyle: "normal",
		fontWeight: "normal",
		textAlign: "left",
		width: 234,
		height: 20,
	},
	labelNineText: {
		backgroundColor: "transparent",
		color: "rgba(0, 0, 0, 0.8)",
		//fontFamily: "Roboto-Regular",
		fontSize: 17,
		fontStyle: "normal",
		fontWeight: "normal",
		textAlign: "left",
		marginLeft: 4,
	},
	imageNineImage: {
		backgroundColor: "transparent",
		resizeMode: "center",
		flex: 1,
		height: 32,
		marginLeft: 20,
	},
	seperator3View: {
		backgroundColor: "rgb(192, 192, 192)",
		height: 2,
		marginLeft: 4,
		marginTop: 7,
	},
	viewSevenView: {
		backgroundColor: "transparent",
		height: 61,
		marginRight: 4,
		marginTop: 13,
	},
	game2View: {
		backgroundColor: "white",
		position: "absolute",
		left: 0,
		width: 375,
		top: 0,
		height: 78,
	},
	imageEightImage: {
		backgroundColor: "transparent",
		resizeMode: "center",
		width: 63,
		height: 59,
	},
	labelEightText: {
		backgroundColor: "transparent",
		color: "rgba(0, 0, 0, 0.8)",
		//fontFamily: "Roboto-Regular",
		fontSize: 17,
		fontStyle: "normal",
		fontWeight: "normal",
		textAlign: "left",
		width: 234,
		height: 20,
	},
	labelSevenText: {
		backgroundColor: "transparent",
		color: "rgba(0, 0, 0, 0.8)",
		//fontFamily: "Roboto-Regular",
		fontSize: 17,
		fontStyle: "normal",
		fontWeight: "normal",
		textAlign: "left",
		marginLeft: 4,
	},
	imageSevenImage: {
		backgroundColor: "transparent",
		resizeMode: "center",
		flex: 1,
		height: 32,
		marginLeft: 20,
	},
	seperator2View: {
		backgroundColor: "rgb(192, 192, 192)",
		height: 1,
		marginLeft: 4,
		marginTop: 5,
	},
	viewSixView: {
		backgroundColor: "transparent",
		height: 76,
		marginLeft: 4,
		marginTop: 4,
	},
	game3View: {
		backgroundColor: "white",
		position: "absolute",
		left: 0,
		width: 375,
		top: 0,
		height: 78,
	},
	imageSixImage: {
		resizeMode: "center",
		backgroundColor: "transparent",
		width: 63,
		height: 59,
	},
	labelSixText: {
		backgroundColor: "transparent",
		color: "rgba(0, 0, 0, 0.8)",
		//fontFamily: "Roboto-Regular",
		fontSize: 17,
		fontStyle: "normal",
		fontWeight: "normal",
		textAlign: "left",
		width: 234,
		height: 20,
	},
	labelFiveText: {
		backgroundColor: "transparent",
		color: "rgba(0, 0, 0, 0.8)",
		//fontFamily: "Roboto-Regular",
		fontSize: 17,
		fontStyle: "normal",
		fontWeight: "normal",
		textAlign: "left",
		marginLeft: 4,
	},
	imageFiveImage: {
		resizeMode: "center",
		backgroundColor: "transparent",
		flex: 1,
		height: 32,
		marginLeft: 20,
	},
	seperator1View: {
		backgroundColor: "rgb(192, 192, 192)",
		height: 1,
		marginLeft: 4,
		marginTop: 3,
	},
	viewFiveView: {
		backgroundColor: "transparent",
		height: 66,
		marginLeft: 4,
		marginTop: 4,
	},
	game4View: {
		backgroundColor: "white",
		position: "absolute",
		left: 0,
		width: 375,
		top: 0,
		height: 78,
	},
	imageFourImage: {
		resizeMode: "center",
		backgroundColor: "transparent",
		width: 63,
		height: 59,
	},
	labelFourText: {
		backgroundColor: "transparent",
		color: "rgba(0, 0, 0, 0.8)",
		//fontFamily: "Roboto-Regular",
		fontSize: 17,
		fontStyle: "normal",
		fontWeight: "normal",
		textAlign: "left",
		width: 234,
		height: 20,
	},
	labelThreeText: {
		color: "rgba(0, 0, 0, 0.8)",
		//fontFamily: "Roboto-Regular",
		fontSize: 17,
		fontStyle: "normal",
		fontWeight: "normal",
		textAlign: "left",
		backgroundColor: "transparent",
		marginLeft: 4,
	},
	imageThreeImage: {
		backgroundColor: "transparent",
		resizeMode: "center",
		flex: 1,
		height: 32,
		marginLeft: 20,
	},
	seperator4View: {
		backgroundColor: "rgb(192, 192, 192)",
		height: 1,
		marginLeft: 4,
		marginTop: 14,
	},
	viewFourView: {
		backgroundColor: "transparent",
		height: 66,
		marginLeft: 4,
		marginTop: 4,
	},
	game5View: {
		backgroundColor: "white",
		position: "absolute",
		left: 0,
		width: 375,
		top: 0,
		height: 78,
	},
	imageTwoImage: {
		resizeMode: "center",
		backgroundColor: "transparent",
		width: 63,
		height: 59,
	},
	labelTwoText: {
		backgroundColor: "transparent",
		color: "rgba(0, 0, 0, 0.8)",
		//fontFamily: "Roboto-Regular",
		fontSize: 17,
		fontStyle: "normal",
		fontWeight: "normal",
		textAlign: "left",
		width: 234,
		height: 20,
	},
	labelText: {
		color: "rgba(0, 0, 0, 0.8)",
		//fontFamily: "Roboto-Regular",
		fontSize: 17,
		fontStyle: "normal",
		fontWeight: "normal",
		textAlign: "left",
		backgroundColor: "transparent",
		marginLeft: 4,
	},
	imageImage: {
		backgroundColor: "transparent",
		resizeMode: "center",
		flex: 1,
		height: 32,
		marginLeft: 20,
	},
	seperator5View: {
		backgroundColor: "rgb(192, 192, 192)",
		height: 1,
		marginLeft: 4,
		marginTop: 9,
	},
	seperatorView: {
		backgroundColor: "rgb(192, 192, 192)",
		height: 1,
		marginTop: 7,
	},
	historyText:{
		textAlign: "center",
      fontSize: 23,
      color: "#ddd",
      fontWeight: "bold"
	}
})

export default styles
