export const AVATAR_INIT = 'avatar_initialize'
export const AVATAR_UPLOADING = 'AVATAR_UPLOADING'
export const AVATAR_UPLOAD_FAILED = 'AVATAR_FAILED'
export const AVATAR_UPLOAD_COMPLETED = 'AVATAR_UPLOADCOMPLETED'
export const LAST_LOGGEDOUT_SCREEN = 'LOGGEDOUT_SCREEN'
export const GAME_REVIEWS = 'GAME_REVIEWS'
export const GAME_REVIEWS_HIDING = "GAME_REVIEWS_HIDING"
export const GAME_ID = 'GAME_ID'
export const GAME_REVIEWS_DATA = "GAME_REVIEWS_DATA"
export const GAME_REVIEWS_RESPONSE_TYPE = "GAME_REVIEWS_RESPONSE_TYPE"
export const UGC_TAB_TYPE = "UGC_TAB_TYPE"
export const AVERAGE_GAMERATING = "AVERAGE_GAMERATING"
export const PROGRESS_DATA = "PROGRESS_DATA"

