//
//  GameFeed1StyleSheet.js
//  Search
//
//  Created by Supernova.
//  Copyright © 2018 Supernova. All rights reserved.
//

import { StyleSheet } from "react-native"

const styles = StyleSheet.create({
	welcomeView: {
		//backgroundColor: "white",
		//flex: 1,
	},
	viewView: {
		width: "100%",
		height: "100%",
	},
	viewViewLinearGradient: {
		position: "absolute",
		left: 0,
		right: 0,
		top: 0,
		height: 74,
	},
	imageTwoImage: {
		//resizeMode: "center",
		backgroundColor: "transparent",
		width: 25,
		height: 25,
		marginTop:8
	},
	labelText: {
		backgroundColor: "transparent",
		color: "white",
		//fontFamily: "TimesNewRomanPS-BoldMT",
		fontSize: 22,
		fontStyle: "normal",
		fontWeight: "bold",
		textAlign: "left",
		width: 163,
		height: 26,
		marginLeft: 12,
		marginTop: 7,
	},
	imageImage: {
		//resizeMode: "center",
		backgroundColor: "transparent",
		width: 25,
		height: 25,
		marginTop:8
	},
	viewTwoView: {
		backgroundColor: "white",
		position: "absolute",
		left: 3,
		right: 0,
		top: 0,
		height: 674,
	},
	// viewNineView: {
	// 	backgroundColor: "transparent",
	// 	//height: 195,
	// },
	// viewScrollView: {
	// 	backgroundColor: "white",
	// 	height: 613,
	// 	marginTop: 1,
	// },
	// labelSevenText: {
	// 	backgroundColor: "transparent",
	// 	color: "rgba(129, 125, 125, 0.75)",
	// 	//fontFamily: ".SFNSText",
	// 	fontSize: 14,
	// 	fontStyle: "normal",
	// 	fontWeight: "normal",
	// 	textAlign: "left",
	// 	alignSelf: "flex-end",
	// 	marginRight: 13,
	// },
	// viewThreeView: {
	// 	backgroundColor: "white",
	// 	height: 184,
	// 	marginTop: 177,
	// },
	labelSixText: {
		backgroundColor: "transparent",
		color: "rgba(129, 125, 125, 0.75)",
		//fontFamily: ".SFNSText",
		fontSize: 14,
		fontStyle: "normal",
		fontWeight: "normal",
		textAlign: "left",
		alignSelf: "flex-end",
		marginRight: 10,
	},
	labelFiveText: {
		backgroundColor: "transparent",
		color: "rgba(0, 0, 0, 0.73)",
		//fontFamily: "Roboto-Medium",
		fontSize: 20,
		fontStyle: "normal",
		fontWeight: "normal",
		textAlign: "left",
		alignSelf: "flex-start",
		width: 324,
		height: 24,
		marginTop: 52,
	},
	imageThreeImage: {
		resizeMode: "center",
		backgroundColor: "transparent",
		width: 115,
		height: 44,
	},
	viewFourView: {
		backgroundColor: "white",
		height: 27,
		marginRight: 1,
		marginTop: 6,
	},
	imageFourImage: {
		backgroundColor: "transparent",
		resizeMode: "center",
		position: "absolute",
		left: 68,
		width: 18,
		top: 544,
		height: 18,
	},
	imageSixImage: {
		backgroundColor: "transparent",
		resizeMode: "center",
		width: 18,
		height: 18,
		marginTop: 4,
	},
	imageFiveImage: {
		backgroundColor: "transparent",
		resizeMode: "center",
		width: 18,
		height: 18,
		marginLeft: 10,
		marginTop: 4,
	},
	labelTwoText: {
		backgroundColor: "transparent",
		color: "black",
		////fontFamily: "Roboto-Regular",
		fontSize: 14,
		fontStyle: "normal",
		fontWeight: "normal",
		textAlign: "left",
		marginLeft: 18,
		marginTop: 6,
	},
	viewSixView: {
		backgroundColor: "white",
		height: 213,
	},
	viewFiveView: {
		backgroundColor: "rgba(137, 131, 131, 0.59)",
		height: 1,
	},
	imageSevenImage: {
		//resizeMode: "center",
		backgroundColor: "transparent",
		borderRadius: 30,
		width: 60,
		height: 60,
	},
	labelNineText: {
		color: "rgba(0, 0, 0, 0.77)",
		//fontFamily: "Roboto-Medium",
		fontSize: 15,
		fontStyle: "normal",
		fontWeight: "normal",
		//textAlign: "left",
		backgroundColor: "transparent",
		marginLeft:12,
		marginTop:10
		// width: 171,
		// height: 21,
	},
	labelEightText: {
		color: "rgba(129, 125, 125, 0.75)",
		//fontFamily: ".SFNSText",
		fontSize: 14,
		fontStyle: "normal",
		fontWeight: "normal",
		textAlign: "left",
		backgroundColor: "transparent",
		marginTop: 4,
	},
	// imageNineImage: {
	// 	//resizeMode: "center",
	// 	backgroundColor: "transparent",
	// 	alignSelf: "flex-end",
	// 	width: 18,
	// 	height: 18,
	// 	marginRight: 90,
	// 	marginTop: 100,
	// },
	// viewSevenView: {
	// 	backgroundColor: "white",
	// 	position: "absolute",
	// 	left: 13,
	// 	right: 8,
	// 	top: 378,
	// 	height: 27,
	// },
	labelTenText: {
		////fontFamily: "Roboto-Regular",
		fontSize: 14,
		fontStyle: "normal",
		fontWeight: "normal",
		marginLeft:15,
		//backgroundColor: "transparent",
		// position: "absolute",
		// right: 14,
		// width: 59,
		// top: 382,
	},
	imageEightImage: {
		resizeMode: "center",
		backgroundColor: "transparent",
		position: "absolute",
		right: 87,
		width: 18,
		top: 384,
		height: 18,
	},
	viewEightView: {
		backgroundColor: "rgba(120, 117, 117, 0.42)",
		height: 1,
	},
	imageTwelveImage: {
		//resizeMode: "center",
		backgroundColor: "transparent",
		borderRadius: 30,
		width: 60,
		height: 60,
	},
	labelSeventeenText: {
		color: "rgba(129, 125, 125, 0.75)",
		////fontFamily: "Roboto-Regular",
		fontSize: 13,
		fontStyle: "normal",
		fontWeight: "normal",
		//textAlign: "left",
		backgroundColor: "transparent",
		marginLeft: 12,
		 marginTop: 6,
	},
	labelSixteenText: {
		color: "rgba(129, 125, 125, 0.75)",
		//fontFamily: ".SFNSText",
		fontSize: 13,
		fontStyle: "normal",
		fontWeight: "normal",
		//textAlign: "left",
		backgroundColor: "transparent",
		marginTop: 10,
		marginLeft:70,
		

	},
	labelFifteenText: {
		color: "rgba(0, 0, 0, 0.73)",
		//fontFamily: "Roboto-Medium",
		fontSize: 15,
		fontStyle: "normal",
		fontWeight: "normal",
		//textAlign: "left",
		backgroundColor: "transparent",
		alignSelf: "flex-start",
		// width: 324,
		// height: 24,
		marginLeft: 18,
		marginTop: 20,
	},
	labelFourteenText: {
		color: "rgba(126, 124, 124, 0.71)",
		////fontFamily: "Roboto-Regular",
		fontSize: 13,
		fontStyle: "normal",
		fontWeight: "normal",
		textAlign: "left",
		backgroundColor: "transparent",
		//height: 54,
		marginLeft: 18,
		marginRight: 8,
		marginTop: 4,
	},
	imageElevenImage: {
		resizeMode: "center",
		backgroundColor: "transparent",
		width: 18,
		height: 18,
		marginTop: 1,
	},
	labelThirteenText: {
		color: "black",
		////fontFamily: "Roboto-Regular",
		fontSize: 15,
		fontStyle: "normal",
		fontWeight: "normal",
		textAlign: "left",
		backgroundColor: "transparent",
		marginLeft: 8,
	},
	imageTenImage: {
		resizeMode: "center",
		backgroundColor: "transparent",
		width: 18,
		height: 18,
		marginLeft: 22,
		marginTop: 1,
	},
	labelTwelveText: {
		color: "black",
		////fontFamily: "Roboto-Regular",
		fontSize: 15,
		fontStyle: "normal",
		fontWeight: "normal",
		textAlign: "left",
		backgroundColor: "transparent",
		marginLeft: 10,
		marginTop: 1,
	},
	labelEighteenText: {
		color: "rgba(0, 0, 0, 0.77)",
		//fontFamily: "Roboto-Medium",
		fontSize: 18,
		fontStyle: "normal",
		fontWeight: "normal",
		textAlign: "left",
		backgroundColor: "transparent",
		position: "absolute",
		left: 92,
		width: 171,
		top: 214,
		height: 21,
	},
	imageThirteenImage: {
		resizeMode: "stretch",
		backgroundColor: "transparent",
		height: 130,
		width:"100%",
		
	},
	labelTwentyTwoText: {
		color: "rgba(0, 0, 0, 0.79)",
		////fontFamily: "Roboto-Regular",
		fontSize: 20,
		fontStyle: "normal",
		fontWeight: "normal",
		textAlign: "left",
		backgroundColor: "transparent",
		height: 24,
		marginLeft: 14,
		marginRight: 149,
		marginTop: 11,
	},
	labelTwentyOneText: {
		color: "rgb(122, 119, 119)",
		////fontFamily: "Roboto-Regular",
		fontSize: 15,
		fontStyle: "normal",
		fontWeight: "normal",
		textAlign: "left",
		backgroundColor: "transparent",
		width: 91,
	},
	labelTwentyText: {
		color: "rgb(122, 119, 119)",
		////fontFamily: "Roboto-Regular",
		fontSize: 15,
		fontStyle: "normal",
		fontWeight: "normal",
		textAlign: "left",
		backgroundColor: "transparent",
		width: 92,
		marginLeft: 18,
	},
	labelNineteenText: {
		color: "rgb(122, 119, 119)",
		////fontFamily: "Roboto-Regular",
		fontSize: 15,
		fontStyle: "normal",
		fontWeight: "normal",
		textAlign: "left",
		backgroundColor: "transparent",
		width: 92,
		marginLeft: 25,
	},
	imageFifteenImage: {
		resizeMode: "center",
		backgroundColor: "transparent",
		width: 18,
		height: 18,
	},
	labelTwentyFourText: {
		color: "white",
		//fontFamily: ".SFNSText",
		fontSize: 14,
		fontStyle: "normal",
		fontWeight: "normal",
		textAlign: "left",
		backgroundColor: "transparent",
		width: 22,
		marginLeft: 8,
	},
	imageFourteenImage: {
		resizeMode: "center",
		backgroundColor: "transparent",
		width: 18,
		height: 18,
		marginLeft: 10,
	},
	labelTwentyThreeText: {
		color: "white",
		//fontFamily: ".SFNSText",
		fontSize: 14,
		fontStyle: "normal",
		fontWeight: "normal",
		textAlign: "left",
		backgroundColor: "transparent",
		width: 23,
		marginLeft: 11,
	},

	// headerView: {
	// 	position: "absolute",
	// 	left: 0,
	// 	right: 0,
	// 	top: 0,
	// },
	
	
	labelTwoText1: {
		backgroundColor: "transparent",
		color: "white",
		//fontFamily: ".SFNSText",
		fontSize: 17,
		fontStyle: "normal",
		fontWeight: "normal",
		textAlign: "left",
		position: "absolute",
		left: 162,
		top: 149,
	},
	gameimageImage: {
		resizeMode: "stretch",
		backgroundColor: "transparent",
		// position: "absolute",
		// left: 0,
		// right: 0,
		// top: 0,
		 height: 200,
		 width:"100%"
	},
	
	labelFourText: {
		backgroundColor: "transparent",
		color: "white",
		//fontFamily: ".SFNSText",
		fontSize: 17,
		fontStyle: "normal",
		fontWeight: "bold",
		textAlign: "left",
		marginLeft: 10,
	},
	
	labelThreeText: {
		color: "white",
		//fontFamily: ".SFNSText",
		fontSize: 17,
		fontStyle: "normal",
		fontWeight: "bold",
		//textAlign: "left",
		backgroundColor: "transparent",
		width: 16,
		marginLeft: 10,
	},





	labelSevenText1: {
		color: "rgba(0, 0, 0, 0.67)",
		//fontFamily: "Roboto-Regular",
		fontSize: 14,
		fontStyle: "normal",
		fontWeight: "normal",
		
		backgroundColor: "transparent",
	},
	labelSixText1: {
		color: "rgba(0, 0, 0, 0.7)",
		//fontFamily: "Roboto-Regular",
		fontSize: 14,
		fontStyle: "normal",
		fontWeight: "normal",
		marginLeft:40,
		backgroundColor: "transparent",
	},
	labelFiveText1: {
		backgroundColor: "transparent",
		color: "rgba(0, 0, 0, 0.7)",
		//fontFamily: "Roboto-Regular",
		fontSize: 14,
		fontStyle: "normal",
		fontWeight: "normal",
		marginLeft:40
	},
	viewScrollView1: {
		backgroundColor: "white",
		borderWidth: 1,
		borderColor: "rgba(255, 255, 255, 0.79)",
		borderStyle: "solid",
		position: "absolute",
		left: 0,
		right: 0,
		top: 0,
		height: 74,
	},
	viewFiveView1: {
		backgroundColor: "white",
		borderWidth: 0.5,
		borderColor: "rgba(192, 192, 192, 0.79)",
		//borderStyle: "solid",
		//height: 1,
		marginTop: 15,
		width:270,
		height:0
		
	},
	labelEightText1: {
		color: "black",
		//fontFamily: "Roboto-Regular",
		fontSize: 17,
		fontStyle: "normal",
		fontWeight: "normal",
		textAlign: "left",
		backgroundColor: "transparent",
	},
	profile_image: {
		width:60,
		height:60,
		borderRadius:30,
		//position:'absolute',
		marginLeft:18,
	},
	comments_container: {
		marginTop: 20,
	},
	username: {
		marginLeft: 12,
		fontSize: 17,
		color:"black",
	},
	comment_time: {
		color: "rgba(129, 125, 125, 0.75)",
	},
	comment: {
		color: "rgba(129, 125, 125, 0.75)",
		////fontFamily: "Roboto-Regular",
		fontSize: 13,
	}
})

export default styles
