//
//  GameFeed2StyleSheet.js
//  Search
//
//  Created by Supernova.
//  Copyright © 2018 Supernova. All rights reserved.
//

import { StyleSheet } from "react-native"

const styles = StyleSheet.create({
	loginView: {
		backgroundColor: "white",
		flex: 1,
	},
	viewViewLinearGradient: {
		position: "absolute",
		left: 0,
		right: 0,
		top: 0,
		height: 74,
	},
	viewView: {
		width: "100%",
		height: "100%",
	},
	imageTwoImage: {
		resizeMode: "center",
		backgroundColor: "transparent",
		width: 44,
		height: 44,
	},
	labelText: {
		color: "white",
		//////fontFamily: "Roboto-Regular",
		fontSize: 20,
		fontStyle: "normal",
		fontWeight: "normal",
		textAlign: "left",
		backgroundColor: "transparent",
		width: 164,
		height: 24,
		marginLeft: 10,
		marginTop: 7,
	},
	imageImage: {
		backgroundColor: "transparent",
		resizeMode: "center",
		width: 44,
		height: 44,
	},
	viewScrollView: {
		backgroundColor: "white",
		position: "absolute",
		left: 0,
		right: 0,
		top: 0,
		height: 804,
	},
	imageFifteenImage: {
		backgroundColor: "rgba(27, 26, 26, 1)",
		borderRadius: 30,
		borderWidth: 1,
		borderColor: "black",
		borderStyle: "solid",
		resizeMode: "center",
		width: 60,
		height: 60,
	},
	viewSixView: {
		backgroundColor: "rgb(224, 224, 224)",
		borderRadius: 10,
		flex: 1,
		height: 100,
		marginLeft: 13,
	},
	imageFourteenImage: {
		backgroundColor: "transparent",
		resizeMode: "center",
		width: 18,
		height: 18,
	},
	labelFourteenText: {
		backgroundColor: "transparent",
		color: "rgb(150, 147, 147)",
		//////fontFamily: "Roboto-Regular",
		fontSize: 15,
		fontStyle: "normal",
		fontWeight: "normal",
		textAlign: "left",
		width: 22,
		marginLeft: 10,
	},
	imageThirteenImage: {
		backgroundColor: "transparent",
		resizeMode: "center",
		width: 18,
		height: 18,
		marginRight: 6,
	},
	labelTwelveText: {
		backgroundColor: "transparent",
		color: "rgb(138, 136, 136)",
		//////fontFamily: "Roboto-Regular",
		fontSize: 15,
		fontStyle: "normal",
		fontWeight: "normal",
		textAlign: "left",
		width: 63,
	},
	imageTwelveImage: {
		backgroundColor: "transparent",
		resizeMode: "center",
		width: 18,
		height: 18,
		marginTop: 1,
	},
	labelThirteenText: {
		backgroundColor: "transparent",
		color: "rgb(138, 136, 136)",
		//////fontFamily: "Roboto-Regular",
		fontSize: 15,
		fontStyle: "normal",
		fontWeight: "normal",
		textAlign: "left",
		width: 64,
		marginLeft: 10,
	},
	imageElevenImage: {
		backgroundColor: "rgba(27, 26, 26, 1)",
		borderRadius: 20,
		borderWidth: 1,
		borderColor: "black",
		borderStyle: "solid",
		resizeMode: "center",
		width: 40,
		height: 40,
		marginTop: 3,
	},
	viewFiveView: {
		backgroundColor: "rgb(224, 224, 224)",
		borderRadius: 10,
		flex: 1,
		height: 100,
		marginLeft: 9,
	},
	imageTenImage: {
		backgroundColor: "transparent",
		resizeMode: "center",
		width: 18,
		height: 18,
		marginTop: 1,
	},
	labelEightText: {
		backgroundColor: "transparent",
		color: "rgb(153, 149, 149)",
		//////fontFamily: "Roboto-Regular",
		fontSize: 12,
		fontStyle: "normal",
		fontWeight: "normal",
		textAlign: "left",
		width: 22,
		marginLeft: 8,
	},
	imageNineImage: {
		backgroundColor: "transparent",
		resizeMode: "center",
		width: 18,
		height: 18,
		marginRight: 5,
		marginTop: 1,
	},
	labelSevenText: {
		backgroundColor: "transparent",
		color: "rgb(138, 136, 136)",
		//////fontFamily: "Roboto-Regular",
		fontSize: 12,
		fontStyle: "normal",
		fontWeight: "normal",
		textAlign: "left",
		width: 64,
	},
	imageEightImage: {
		backgroundColor: "rgba(27, 26, 26, 1)",
		borderRadius: 30,
		borderWidth: 1,
		borderColor: "black",
		borderStyle: "solid",
		resizeMode: "center",
		width: 60,
		height: 60,
	},
	viewFourView: {
		backgroundColor: "rgb(224, 224, 224)",
		borderRadius: 10,
		flex: 1,
		height: 100,
		marginLeft: 9,
	},
	imageSevenImage: {
		backgroundColor: "transparent",
		resizeMode: "center",
		width: 18,
		height: 18,
		marginTop: 1,
	},
	labelThreeText: {
		backgroundColor: "transparent",
		color: "rgb(150, 147, 147)",
		//fontFamily: ".SFNSText",
		fontSize: 14,
		fontStyle: "normal",
		fontWeight: "normal",
		textAlign: "left",
		width: 22,
		marginLeft: 8,
	},
	imageSixImage: {
		backgroundColor: "transparent",
		resizeMode: "center",
		width: 18,
		height: 18,
		marginRight: 10,
		marginTop: 1,
	},
	labelTwoText: {
		backgroundColor: "transparent",
		color: "rgb(138, 136, 136)",
		//fontFamily: ".SFNSText",
		fontSize: 14,
		fontStyle: "normal",
		fontWeight: "normal",
		textAlign: "left",
		width: 63,
	},
	viewTwoView: {
		backgroundColor: "white",
		height: 55,
		marginTop: 90,
	},
	imageFiveImage: {
		backgroundColor: "rgba(27, 26, 26, 1)",
		borderRadius: 20,
		borderWidth: 1,
		borderColor: "black",
		borderStyle: "solid",
		resizeMode: "center",
		width: 40,
		height: 40,
	},
	viewThreeView: {
		backgroundColor: "white",
		borderRadius: 20,
		shadowColor: "rgb(179, 174, 174)",
		shadowRadius: 1,
		shadowOpacity: 1,
		flex: 1,
		height: 40,
		marginLeft: 14,
	},
	textFieldTextInput: {
		backgroundColor: "transparent",
		padding: 0,
		color: "black",
		//fontFamily: ".SFNSText",
		fontSize: 12,
		fontStyle: "normal",
		fontWeight: "normal",
		textAlign: "left",
		flex: 1,
		height: 27,
		marginRight: 5,
	},
	imageFourImage: {
		backgroundColor: "transparent",
		resizeMode: "center",
		width: 18,
		height: 18,
		marginRight: 15,
		marginTop: 4,
	},
	imageThreeImage: {
		backgroundColor: "transparent",
		resizeMode: "center",
		width: 18,
		height: 18,
		marginTop: 4,
	},
	labelSixText: {
		backgroundColor: "transparent",
		color: "black",
		//////fontFamily: "Roboto-Regular",
		fontSize: 15,
		fontStyle: "normal",
		fontWeight: "normal",
		textAlign: "left",
		width: 168,
		height: 18,
	},
	labelFiveText: {
		backgroundColor: "transparent",
		color: "rgb(175, 171, 171)",
		//////fontFamily: "Roboto-Regular",
		fontSize: 12,
		fontStyle: "normal",
		fontWeight: "normal",
		textAlign: "left",
		marginTop: 6,
	},
	labelFourText: {
		backgroundColor: "transparent",
		color: "rgba(146, 142, 142, 0.83)",
		//////fontFamily: "Roboto-Regular",
		fontSize: 15,
		fontStyle: "normal",
		fontWeight: "normal",
		textAlign: "left",
		height: 54,
		marginRight: 13,
		marginTop: 8,
	},
	labelTenText: {
		backgroundColor: "transparent",
		color: "rgb(175, 171, 171)",
		//////fontFamily: "Roboto-Regular",
		fontSize: 12,
		fontStyle: "normal",
		fontWeight: "normal",
		textAlign: "left",
		alignSelf: "flex-end",
	},
	labelNineText: {
		backgroundColor: "transparent",
		color: "rgba(146, 142, 142, 0.83)",
		//////fontFamily: "Roboto-Regular",
		fontSize: 12,
		fontStyle: "normal",
		fontWeight: "normal",
		textAlign: "left",
		height: 42,
		marginRight: 11,
		marginTop: 8,
	},
	labelElevenText: {
		backgroundColor: "transparent",
		color: "black",
		//////fontFamily: "Roboto-Regular",
		fontSize: 12,
		fontStyle: "normal",
		fontWeight: "normal",
		textAlign: "left",
		position: "absolute",
		left: 160,
		width: 117,
		top: 191,
		height: 14,
	},
	labelSeventeenText: {
		backgroundColor: "transparent",
		color: "black",
		//////fontFamily: "Roboto-Regular",
		fontSize: 15,
		fontStyle: "normal",
		fontWeight: "normal",
		textAlign: "left",
		width: 167,
		height: 18,
	},
	labelSixteenText: {
		backgroundColor: "transparent",
		color: "rgb(175, 171, 171)",
		//fontFamily: ".SFNSText",
		fontSize: 10,
		fontStyle: "normal",
		fontWeight: "normal",
		textAlign: "left",
		marginTop: 3,
	},
	labelFifteenText: {
		color: "rgba(146, 142, 142, 0.83)",
		//////fontFamily: "Roboto-Regular",
		fontSize: 12,
		fontStyle: "normal",
		fontWeight: "normal",
		textAlign: "left",
		backgroundColor: "transparent",
		height: 42,
		marginTop: 8,
	},
})

export default styles
