//
//  TrendingGamesStyleSheet.js
//  My Profile
//
//  Created by Supernova.
//  Copyright © 2018 S7works.io. All rights reserved.
//

import { StyleSheet } from "react-native"

const styles = StyleSheet.create({
	signupView: {
		backgroundColor: "white",
		flex: 1,
	},
	viewView: {
		backgroundColor: "rgb(8, 67, 159)",
		position: "absolute",
		left: 0,
		right: 0,
		top: 0,
		height: 78,
	},
	imageTwoImage: {
		//resizeMode: "center",
		backgroundColor: "transparent",
		width: 20,
		height: 20,
		marginTop:10,
		marginLeft:5
	},
	labelText: {
		color: "white",
		//fontFamily: "Roboto-Regular",
		fontSize: 20,
		fontStyle: "normal",
		fontWeight: "normal",
		textAlign: "left",
		backgroundColor: "transparent",
		flex: 1,
		marginLeft: 18,
		marginRight: 81,
		marginTop: 8,
	},
	imageImage: {
		//resizeMode: "center",
		backgroundColor: "transparent",
		width: 25,
		height: 30,
		marginTop:10,
		
	},
	viewScrollView: {
		backgroundColor: "white",
		position: "absolute",
		left: 0,
		right: 0,
		top: 0,
		height: 758,
	},
	labelFiveText: {
		color: "white",
		//fontFamily: ".SFNSText",
		fontSize: 14,
		fontStyle: "normal",
		fontWeight: "normal",
		textAlign: "left",
		backgroundColor: "transparent",
		alignSelf: "stretch",
		marginLeft: 21,
		marginRight: 204,
	},
	labelNineText: {
		backgroundColor: "transparent",
		color: "white",
		//fontFamily: ".SFNSText",
		fontSize: 12,
		fontStyle: "normal",
		fontWeight: "normal",
		textAlign: "left",
		alignSelf: "stretch",
		marginLeft: 25,
		marginRight: 200,
		marginTop: 146,
	},
	viewTwoView: {
		backgroundColor: "white",
		width: 375,
		height: 146,
	},
	viewThreeView: {
		backgroundColor: "white",
		width: 375,
		height: 146,
	},
	imageThreeImage: {
		backgroundColor: "transparent",
		borderRadius: 10,
		borderWidth: 1,
		borderColor: "rgb(159, 149, 149)",
		borderStyle: "solid",
		//resizeMode: "center",
		width: 167,
		height: 138,
	},
	imageFourImage: {
		//resizeMode: "center",
		backgroundColor: "transparent",
		borderRadius: 10,
		borderWidth: 1,
		borderColor: "rgb(159, 149, 149)",
		borderStyle: "solid",
		width: 167,
		height: 138,
	},
	labelTwoText: {
		backgroundColor: "transparent",
		color: "white",
		//fontFamily: "Roboto-Regular",
		fontSize: 12,
		fontStyle: "normal",
		fontWeight: "normal",
		textAlign: "left",
		position: "absolute",
		left: 25,
		right: 200,
		top: 567,
	},
	labelFourText: {
		backgroundColor: "transparent",
		color: "white",
		////fontFamily: "Roboto-Regular",
		fontSize: 15,
		fontStyle: "normal",
		fontWeight: "normal",
		textAlign: "left",
	},
	labelThreeText: {
		backgroundColor: "transparent",
		color: "white",
		////fontFamily: "Roboto-Regular",
		fontSize: 12,
		fontStyle: "normal",
		fontWeight: "normal",
		textAlign: "left",
		marginRight: 1,
		marginTop: 4,
	},
	imageFiveImage: {
		//resizeMode: "center",
		backgroundColor: "transparent",
		borderRadius: 10,
		borderWidth: 1,
		borderColor: "rgb(159, 149, 149)",
		borderStyle: "solid",
		width: 167,
		height: 138,
	},
	imageSixImage: {
		backgroundColor: "transparent",
		borderRadius: 10,
		borderWidth: 1,
		borderColor: "rgb(159, 149, 149)",
		borderStyle: "solid",
		//resizeMode: "center",
		width: 167,
		height: 138,
	},
	labelSevenText: {
		color: "white",
		//fontFamily: "Roboto-Regular",
		fontSize: 15,
		fontStyle: "normal",
		fontWeight: "normal",
		textAlign: "left",
		backgroundColor: "transparent",
		marginRight: 4,
	},
	labelSixText: {
		color: "white",
		////fontFamily: "Roboto-Regular",
		fontSize: 12,
		fontStyle: "normal",
		fontWeight: "normal",
		textAlign: "left",
		backgroundColor: "transparent",
		marginLeft: 3,
		marginTop: 4,
	},
	labelEightText: {
		backgroundColor: "transparent",
		color: "white",
		////fontFamily: "Roboto-Regular",
		fontSize: 12,
		fontStyle: "normal",
		fontWeight: "normal",
		textAlign: "left",
		position: "absolute",
		left: 205,
		right: 20,
		top: 416,
	},
	viewFiveView: {
		backgroundColor: "white",
		alignSelf: "center",
		width: 375,
		height: 157,
	},
	viewFourView: {
		backgroundColor: "white",
		alignSelf: "center",
		width: 375,
		height: 145,
	},
	labelTenText: {
		color: "white",
		////fontFamily: "Roboto-Regular",
		fontSize: 15,
		fontStyle: "normal",
		fontWeight: "normal",
		textAlign: "left",
		backgroundColor: "transparent",
		marginLeft: 204,
		marginRight: 20,
		marginTop: 92,
	},
	labelElevenText: {
		backgroundColor: "transparent",
		color: "white",
		////fontFamily: "Roboto-Regular",
		fontSize: 15,
		fontStyle: "normal",
		fontWeight: "normal",
		textAlign: "left",
		marginLeft: 24,
		marginRight: 200,
		marginTop: 133,
	},
	labelFourteenText: {
		backgroundColor: "transparent",
		color: "white",
		//fontFamily: ".SFNSText",
		fontSize: 14,
		fontStyle: "normal",
		fontWeight: "normal",
		textAlign: "left",
		flex: 1,
		marginRight: 23,
		marginTop: 96,
	},
	imageSevenImage: {
		//resizeMode: "center",
		backgroundColor: "transparent",
		borderRadius: 10,
		borderWidth: 1,
		borderColor: "rgb(159, 149, 149)",
		borderStyle: "solid",
		width: 168,
		height: 138,
	},
	imageNineImage: {
		backgroundColor: "transparent",
		borderRadius: 10,
		borderWidth: 1,
		borderColor: "rgb(159, 149, 149)",
		borderStyle: "solid",
		//resizeMode: "center",
		width: 167,
		height: 138,
	},
	imageTenImage: {
		//resizeMode: "center",
		backgroundColor: "transparent",
		borderRadius: 10,
		borderWidth: 1,
		borderColor: "rgb(159, 149, 149)",
		borderStyle: "solid",
		width: 167,
		height: 138,
	},
	labelThirteenText: {
		backgroundColor: "transparent",
		color: "white",
		////fontFamily: "Roboto-Regular",
		fontSize: 15,
		fontStyle: "normal",
		fontWeight: "normal",
		textAlign: "left",
	},
	labelTwelveText: {
		backgroundColor: "transparent",
		color: "white",
		////fontFamily: "Roboto-Regular",
		fontSize: 12,
		fontStyle: "normal",
		fontWeight: "normal",
		textAlign: "left",
		marginRight: 1,
		marginTop: 3,
	},
	imageEightImage: {
		//resizeMode: "center",
		backgroundColor: "transparent",
		borderRadius: 10,
		borderWidth: 1,
		borderColor: "rgb(159, 149, 149)",
		borderStyle: "solid",
		position: "absolute",
		left: 0,
		width: 167,
		top: 10,
		height: 138,
	},
	labelFifteenText: {
		backgroundColor: "transparent",
		color: "white",
		////fontFamily: "Roboto-Regular",
		fontSize: 15,
		fontStyle: "normal",
		fontWeight: "normal",
		textAlign: "left",
		marginRight: 3,
	},
	labelSixteenText: {
		backgroundColor: "transparent",
		color: "white",
		////fontFamily: "Roboto-Regular",
		fontSize: 12,
		fontStyle: "normal",
		fontWeight: "normal",
		textAlign: "left",
		marginLeft: 3,
		marginTop: 3,
	},
	labelEighteenText: {
		backgroundColor: "transparent",
		color: "white",
		////fontFamily: "Roboto-Regular",
		fontSize: 15,
		fontStyle: "normal",
		fontWeight: "normal",
		textAlign: "left",
		marginRight: 4,
	},
	labelSeventeenText: {
		backgroundColor: "transparent",
		color: "white",
		////fontFamily: "Roboto-Regular",
		fontSize: 12,
		fontStyle: "normal",
		fontWeight: "normal",
		textAlign: "left",
		marginLeft: 4,
		marginTop: 4,
	},
	labelTwentyText: {
		backgroundColor: "transparent",
		color: "white",
		////fontFamily: "Roboto-Regular",
		fontSize: 15,
		fontStyle: "normal",
		fontWeight: "normal",
		textAlign: "left",
	},
	labelNineteenText: {
		backgroundColor: "transparent",
		color: "white",
		////fontFamily: "Roboto-Regular",
		fontSize: 12,
		fontStyle: "normal",
		fontWeight: "normal",
		textAlign: "left",
		marginRight: 1,
		marginTop: 4,
	},
})

export default styles
