//
//  UserProfileStyleSheet.js
//  My Profile
//
//  Created by Supernova.
//  Copyright © 2018 S7works.io. All rights reserved.
//

import { StyleSheet } from "react-native"
  
const styles = StyleSheet.create({

	welcomeView: {
		backgroundColor: "transparent",
		//flex: 1,
	},
	viewView: {
		//backgroundColor: "rgb(8, 67, 159)",
		//borderRadius: 55,
		borderBottomLeftRadius: 40,
       borderBottomRightRadius: 40,
		position: "absolute",
		left: 0, 
		right: 0,
		top: 0,
		//height: 144,
	},
	// viewFourView: {
	// 	backgroundColor: "rgb(8, 67, 159)",
	// 	//alignSelf: "stretch",
	// 	height:100,
	// 	borderBottomLeftRadius: 55,
	// 	borderBottomRightRadius: 55,
	// 	//borderRadius: 55,
		
		
	// },
	viewTwoView: {
		backgroundColor: "white",
		borderRadius: 60,
		shadowColor: "rgb(138, 131, 131)",
		shadowRadius: 2,
		shadowOpacity: 1,
		width: 100,
		height: 150,
		marginTop: 3,
	},
	imageTwoImage: {
		//resizeMode: "center",
		backgroundColor: "transparent",
		//flex: 1,
		height: 100,
		width:100,
		borderRadius:50,
	},
	viewThreeView: {
		backgroundColor: "white",
		borderRadius: 20,
		shadowColor: "rgb(107, 104, 104)",
		shadowRadius: 2,
		shadowOpacity: 1,
		width: 35,
		height: 35,
		position: "absolute",
		left: 215,
		//width: 26,
		top: 10,
		//marginTop: 70,
	},
	imageImage: {
		//resizeMode: "center",
		backgroundColor: "transparent",
		position: "absolute",
		left: 223,
		//width: 26,
		top: 20,
		height: 20,
		width:20,
		//borderRadius:20
	},
	viewSixView: {
		backgroundColor: "rgb(8, 67, 159)",
		width: 46,
		height: 44,
	},
	labelText: {
		backgroundColor: "transparent",
		color: "white",
		////fontFamily: "Roboto-Regular",
		fontSize: 20,
		fontStyle: "normal",
		fontWeight: "bold",
		//textAlign: "left",
		marginLeft: 50 ,
		//marginRight: 152,
		marginTop: 30,
	},
	viewFiveView: {
		backgroundColor: "rgb(8, 67, 159)",
		width: 46,
		height: 44,
		marginLeft: 152,
	},
	imageThreeImage: {
		backgroundColor: "transparent",
		//resizeMode: "center",
		position: "absolute",
		right: 21,
		width: 25,
		top: 30,
		height: 25,
	},
	imageFourImage: {
		backgroundColor: "transparent",
		//resizeMode: "center",
		position: "absolute",
		left: 14,
		width: 20,
		top: 30,
		height: 20,
	},
	viewEightView: {
		backgroundColor: "white",
		position: "absolute",
		left: 0,
		right: 0,
		top: 0,
		height: 50,
	},
	labelTenText: {
		backgroundColor: "transparent",
		color: "rgba(16, 42, 89, 0.94)",
		////fontFamily: "Roboto-Regular",
		fontSize: 25,
		fontStyle: "normal",
		fontWeight: "normal",
		textAlign: "center",
		//width: 317,
	},
	labelNineText: {
		backgroundColor: "transparent",
		color: "rgb(62, 60, 60)",
		////fontFamily: "Roboto-Regular",
		fontSize: 15,
		fontStyle: "normal",
		fontWeight: "normal",
		textAlign: "center",
		//width: 184,
		marginTop: 6,
	},
	labelEightText: {
		backgroundColor: "transparent",
		color: "rgb(61, 59, 59)",
		////fontFamily: "Roboto-Regular",
		fontSize: 17,
		fontStyle: "normal",
		fontWeight: "normal",
		textAlign: "center",
		//width: 249,
	},
	viewSevenView: {
		backgroundColor: "white",
		position: "absolute",
		left: 0,
		right: 0,
		top: 0,
		height: 77,
	},
	labelSevenText: {
		color: "rgb(15, 16, 16)",
		////fontFamily: "Roboto-Regular",
		fontSize: 25,
		fontStyle: "normal",
		fontWeight: "normal",
		textAlign: "center",
		backgroundColor: "transparent",
		 
	},
	labelFourText: {
		backgroundColor: "transparent",
		color: "#0C8AE3",
		////fontFamily: "Roboto-Regular",
		fontSize: 18,
		fontStyle: "normal",
		fontWeight: "normal",
		textAlign: "center",
		marginTop: 9,
	},
	labelFiveText: {
		backgroundColor: "transparent",
		color: "rgb(14, 15, 15)",
		////fontFamily: "Roboto-Regular",
		fontSize: 25,
		fontStyle: "normal",
		fontWeight: "normal",
		textAlign: "center",
		 
	},
	labelTwoText: {
		backgroundColor: "transparent",
		color: "#0C8AE3",
		////fontFamily: "Roboto-Regular",
		fontSize: 18,
		fontStyle: "normal",
		fontWeight: "normal",
		textAlign: "center",
		marginTop: 9,
	},
	labelSixText: {
		color: "rgb(24, 24, 24)",
		////fontFamily: "Roboto-Regular",
		fontSize: 25,
		fontStyle: "normal",
		fontWeight: "normal",
		textAlign: "center",
		backgroundColor: "transparent",
		 
	},
	labelThreeText: {
		color: "#0C8AE3",
		////fontFamily: "Roboto-Regular",
		fontSize: 18,
		fontStyle: "normal",
		fontWeight: "normal",
		textAlign: "center",
		backgroundColor: "transparent",
		marginTop: 9,
	},
	// buttonButton: {
	// 	backgroundColor: "white",
	// 	borderRadius: 23,
	// 	borderWidth: 1,
	// 	borderColor: "black",
	// 	borderStyle: "solid",
	// 	flexDirection: "row",
	// 	alignItems: "center",
	// 	justifyContent: "center",
	// 	padding: 0,
	// 	position: "absolute",
	// 	left: 0,
	// 	right: 0,
	// 	top: 0,
	// 	height: 44,
	// },
	// buttonButtonText: {
	// 	color: "rgb(88, 84, 84)",
	// 	////fontFamily: "Roboto-Regular",
	// 	fontSize: 16,
	// 	fontStyle: "normal",
	// 	fontWeight: "bold",
	// 	textAlign: "left",
	// },
	buttonButtonImage: {
		//resizeMode: "contain",
		marginRight: 10,
	},
	imageFiveImage: {
		backgroundColor: "transparent",
		position: "absolute",
		left: 72,
		right: 240,
		top: 10,
		height: 24,
	},
	labelElevenText: {
		color: "black",
		//fontFamily: ".SFNSText",
		fontSize: 14,
		fontStyle: "normal",
		fontWeight: "normal",
		textAlign: "left",
		backgroundColor: "transparent",
		alignSelf: "flex-start",
		marginLeft: 13,
	},
	viewNineView: {
		backgroundColor: "white",
		height: 25,
		marginTop: 57,
	},
	viewScrollView: {
		backgroundColor: "white",
		position: "absolute",
		left: 2,
		width: 375,
		top: 0,
		height: 411,
	},
	labelFourteenText: {
		color: "rgb(34, 200, 241)",
		//fontFamily: ".SFNSText",
		fontSize: 14,
		fontStyle: "normal",
		fontWeight: "normal",
		textAlign: "right",
		backgroundColor: "transparent",
		marginLeft: 310,
		marginRight: 292,
	},
	viewTwoScrollView: {
		backgroundColor: "white",
		alignSelf: "flex-end",
		width: 652,
		height: 130,
		marginTop: 5,
	},
	viewTenView: {
		backgroundColor: "white",
		height: 25,
		marginLeft: 1,
		marginRight: 277,
		marginTop: 9,
	},
	viewThreeScrollView: {
		backgroundColor: "white",
		alignSelf: "flex-end",
		width: 652,
		height: 130,
		marginRight: 1,
		marginTop: 8,
	},
	viewFourScrollView: {
		backgroundColor: "white",
		alignSelf: "flex-end",
		width: 652,
		height: 130,
	},
	labelTwelveText: {
		color: "rgb(90, 86, 86)",
		////fontFamily: "Roboto-Regular",
		fontSize: 15,
		fontStyle: "normal",
		fontWeight: "normal",
		textAlign: "left",
		backgroundColor: "transparent",
		marginLeft:15
	},
	labelThirteenText: {
		backgroundColor: "transparent",
		color: "#0C8AE3",
		////fontFamily: "Roboto-Regular",
		fontSize: 15,
		fontStyle: "normal",
		fontWeight: "normal",
		//textAlign: "right",
		//flex: 1,
		marginRight: 10,
	},
	imageEightImage: {
		backgroundColor: "transparent",
		borderRadius: 6,
		//resizeMode: "center",
		width: 120,
		height: 100,
		marginLeft:15
	},
	imageSevenImage: {
		//resizeMode: "center",
		backgroundColor: "transparent",
		borderRadius: 6,
		width: 120,
		height: 100,
		marginLeft:15
	},
	imageSixImage: {
		//resizeMode: "center",
		backgroundColor: "transparent",
		borderRadius: 6,
		width: 120,
		height: 100,
		marginLeft:15
	},
	imageElevenImage: {
		backgroundColor: "transparent",
		borderRadius: 6,
		//resizeMode: "center",
		width: 150,
		height: 130,
		marginLeft:15
	},
	imageTenImage: {
		//resizeMode: "center",
		backgroundColor: "transparent",
		borderRadius: 6,
		width: 120,
		height: 100,
		marginLeft:15
	},
	imageNineImage: {
		//resizeMode: "center",
		backgroundColor: "transparent",
		borderRadius: 6,
		width: 120,
		height: 100,
		marginLeft:15
	},
	viewElevenView: {
		backgroundColor: "white",
		position: "absolute",
		left: 1,
		right: 277,
		top: 5,
		height: 20,
	},
	labelSixteenText: {
		color: "rgb(90, 86, 86)",
		////fontFamily: "Roboto-Regular",
		fontSize: 15,
		fontStyle: "normal",
		fontWeight: "normal",
		textAlign: "left",
		backgroundColor: "transparent",
		//flex: 1,
		//marginRig: 228,
		marginLeft:15
	},
	labelFifteenText: {
		color: "#0C8AE3",
		////fontFamily: "Roboto-Regular",
		fontSize: 15,
		fontStyle: "normal",
		fontWeight: "normal",
		textAlign: "right",
		backgroundColor: "transparent",
		//flex: 1,
		//marginLeft: 228,
		marginRight:10
	},
	textProfile:{
		color:'#fff',
		fontWeight:'bold',
		fontSize:14,
		position:'absolute',
		bottom:30,
		left:20,
		right:0,
	},
	profilePlayer:{
		color:'#fff',
		fontWeight:'bold',
		fontSize:12,
		position:'absolute',
		bottom:10,
		left:20

	},
	buttonButton: {
		backgroundColor: "rgb(8, 67, 159)",
		borderRadius: 23,
		flexDirection: "row",
		alignItems: "center",
		justifyContent: "center",
		padding: 0,
		height: 44,
		marginLeft: 16,
		marginRight: 16,
		marginTop: 17,
	},
	buttonButtonText: {
		color: "white",
		////fontFamily: "Roboto-Regular",
		fontSize: 18,
		fontStyle: "normal",
		fontWeight: "bold",
		textAlign: "left",
	},
	pro_image:{
		borderRadius:50,
		height:100,
		width:100,
		marginLeft:"38%",
		marginTop:"20%",
	 },
	 img:{
		 top:12,
	 },
	 image_profile:{
		 flex:1,
		 //flexDirection:'row'
	 },

	 // swiping of the image
	 wrapper: {
	},
	slide1: {
	  flex: 1,
	  justifyContent: 'center',
	  alignItems: 'center',
	  backgroundColor: '#9DD6EB'
	},
	slide2: {
	  flex: 1,
	  justifyContent: 'center',
	  alignItems: 'center',
	  backgroundColor: '#97CAE5'
	},
	text: {
		color: '#fff',
		fontSize: 30,
		fontWeight: 'bold'
	  }
})

export default styles
