//
//  WelcomeStyleSheet.js
//  FORGETPASSWORD3
//
//  Created by Supernova.
//  Copyright © 2018 Supernova. All rights reserved.
//

import { StyleSheet } from "react-native"

const styles = StyleSheet.create({
	welcomeView: {
		backgroundColor: "white",
		flex: 1,
		alignItems: "center",
	},
	viewView: {
		backgroundColor: "transparent",
		width: 375,
		height: 58,
	},
	viewTwoView: {
		backgroundColor: "white",
		position: "absolute",
		left: 0,
		right: 0,
		top: 0,
		height: 76,
	},
	imageImage: {
		backgroundColor: "rgba(56, 65, 135, 0.65)",
		resizeMode: "center",
		position: "absolute",
		left: 7,
		right: 339,
		top: 25,
		height: 34,
	},
	labelText: {
		color: "rgba(0, 0, 0, 0.91)",
		//fontFamily: "Roboto-Regular",
		fontSize: 17,
		fontStyle: "normal",
		fontWeight: "normal",
		textAlign: "left",
		backgroundColor: "transparent",
		position: "absolute",
		alignSelf: "center",
		top: 13,
	},
	viewThreeView: {
		backgroundColor: "transparent",
		width: 375,
		height: 305,
		marginTop: 6,
	},
	viewFourView: {
		backgroundColor: "white",
		position: "absolute",
		alignSelf: "center",
		width: 375,
		top: 11,
		height: 294,
	},
	labelTwoText: {
		color: "rgba(0, 0, 0, 0.8)",
		////fontFamily: ".SFNSText",
		fontSize: 19,
		fontStyle: "normal",
		fontWeight: "bold",
		textAlign: "left",
		backgroundColor: "transparent",
		alignSelf: "flex-start",
		width: 281,
		height: 30,
		marginLeft: 20,
		marginTop: 30,
	},
	textFieldTextInput: {
		color: "black",
		fontSize: 15,
		fontStyle: "normal",
		fontWeight: "normal",
		textAlign: "left",
		backgroundColor: "transparent",
		padding: 0,
		// height: 20,
		marginLeft: 2,
		// marginRight: 30,
		marginTop: 0,
	},
	viewSixView: {
		backgroundColor: "black",
		opacity: 0.1,
		height: 1,
		marginLeft: 2,
		// marginRight: 14,
		marginTop: 0,
	},
	textFieldTwoTextInput: {
		backgroundColor: "transparent",
		padding: 0,
		color: "black",
		fontSize: 15,
		fontStyle: "normal",
		fontWeight: "normal",
		textAlign: "left",
		// height: 20,
		marginLeft: 2,
		// marginRight: 30,
		marginTop: 30,
	},
	viewFiveView: {
		backgroundColor: "black",
		opacity: 0.1,
		height: 1,
		marginLeft: 2,
		// marginRight: 14,
		marginTop: 0,
	},
	buttonButtonImage: {
		resizeMode: "contain",
		marginRight: 10,
	},
	buttonButton: {
		backgroundColor: "rgba(162, 159, 159, 0.54)",
		borderRadius: 30, 
		borderWidth: 1,
		borderColor: "rgba(162, 157, 157, 0.65)",
		borderStyle: "solid",
		flexDirection: "row",
		alignItems: "center",
		justifyContent: "center",
		padding: 0,
		alignSelf: "stretch",
		height: 52,  
		marginLeft: 31,
		marginRight: 29,
	},
	buttonButtonText: {
		color: "white",
		//fontFamily: "Tahoma",
		fontSize: 15,
		fontStyle: "normal",
		fontWeight: "normal",
		textAlign: "center",
	},
	ForgotFieldsView: {
		backgroundColor: "white",
		borderRadius: 2,
		alignSelf: "stretch",
		height: 300,
		marginLeft: 20,
		marginRight: 20,
		marginTop: 10,
	},
	changeButton:{
		backgroundColor: "#1D365F",
		borderRadius: 30,
		borderWidth: 1,
		borderColor: "rgba(162, 157, 157, 0.65)",
		borderStyle: "solid",
		flexDirection: "row",
		alignItems: "center",
		justifyContent: "center",
		padding: 0,
		alignSelf: "stretch",
		height: 52,
		marginLeft: 27,
		marginRight: 30,
	},
	changeText:{
		color: "white",
		fontSize: 15,
		fontStyle: "normal",
		fontWeight: "normal",
		textAlign: "center",
	}

})

export default styles
