
import { StyleSheet } from "react-native"

const styles = StyleSheet.create({
	messagesView: {
		backgroundColor: "white",
		flex: 1,
	},
	viewViewLinearGradient: {
		position: "absolute",
		left: 0,
		right: 0,
		top: 0,
		height: 74,
	},
	viewView: {
		width: "100%",
		height: "100%",
	},
	viewTwoView: {
		backgroundColor: "white",
		borderRadius: 20,
		shadowColor: "rgb(144, 141, 141)",
		shadowRadius: 1,
		shadowOpacity: 1,
		position: "absolute",
		left: 12,
		right: 11,
		top: 50,
		height: 47,   
	},
	imageThreeImage: {
		backgroundColor: "transparent",
		resizeMode: "center",
		width: 29,
		height: 40,
	},
	textFieldTextInput: {
		color: "rgba(0, 0, 0, 0.91)",
		fontSize: 15,
		fontStyle: "normal",
		fontWeight: "normal",
		textAlign: "left",
		backgroundColor: "transparent",
		paddingTop: 10,
		flex: 1,
		height: 40,
		marginLeft: 3,
		marginRight: 11,
	},
	imageTwoImage: {
		backgroundColor: "transparent",
		resizeMode: "center",
		width: 29,
		height: 40,
		marginRight: 3,
	},
	imageImage: {
		backgroundColor: "transparent",
		resizeMode: "center",
		width: 29,
		height: 40,
	},
	viewThreeView: {
		backgroundColor: "white",
		position: "absolute",
		left: 0,
		right: 0,
		top: 0,
		height: 639,
	},
	buttonTwoButtonText: {
		color: "black",
		fontSize: 15,
		fontStyle: "normal",
		fontWeight: "normal",
		textAlign: "left",
	},
	buttonTwoButton: {
		backgroundColor: "white",
		flexDirection: "row",
		alignItems: "center",
		justifyContent: "center",
		padding: 0,
		alignSelf: "flex-end",
		width: 78,
		height: 39,
		marginRight: 3,
	},
	buttonTwoButtonImage: {
		resizeMode: "contain",
		marginRight: 10,
	},
	labelSixText: {
		color: "rgba(28, 27, 27, 0.73)",
		fontSize: 20,
		fontStyle: "normal",
		fontWeight: "normal",
		textAlign: "left",
		backgroundColor: "transparent",
		width: 134,
		height: 24,
		marginTop: 11,
	},
	textFieldEightTextInput: {
		backgroundColor: "transparent",
		paddingTop: 10,
		color: "black",
		fontSize: 15,
		fontStyle: "normal",
		fontWeight: "normal",
		textAlign: "left",
		width: 126,
		height: 35,
		marginRight: 17,
	},
	imageTwelveImage: {
		backgroundColor: "transparent",
		resizeMode: "center",
		width: 18,
		height: 18,
		marginTop: 11,
	},
	viewSevenView: {
		backgroundColor: "rgb(224, 224, 224)",
		alignSelf: "flex-end",
		width: 176,
		height: 1,
		marginRight: 3,
		marginTop: 4,
	},
	labelFiveText: {
		color: "rgba(28, 27, 27, 0.73)",
		fontSize: 20,
		fontStyle: "normal",
		fontWeight: "normal",
		textAlign: "left",
		backgroundColor: "transparent",
		alignSelf: "flex-start",
		width: 134,
		height: 24,
		marginTop: 29,
	},
	textFieldSixTextInput: {
		color: "black",
		fontSize: 15,
		fontStyle: "normal",
		fontWeight: "normal",
		textAlign: "left",
		backgroundColor: "transparent",
		paddingTop: 10,
		width: 123,
		height: 35,
	},
	imageFourImage: {
		resizeMode: "center",
		backgroundColor: "transparent",
		width: 18,
		height: 18,
		marginLeft: 11,
		marginTop: 13,
	},
	textFieldFourTextInput: {
		backgroundColor: "transparent",
		paddingTop: 10,
		color: "black",
		fontSize: 15,
		fontStyle: "normal",
		fontWeight: "normal",
		textAlign: "left",
		width: 117,
		height: 35,
		marginRight: 7,
	},
	imageSevenImage: {
		resizeMode: "center",
		backgroundColor: "transparent",
		width: 18,
		height: 18,
		marginTop: 13,
	},
	viewTenView: {
		backgroundColor: "rgb(224, 224, 224)",
		width: 152,
		height: 1,
	},
	viewEightView: {
		backgroundColor: "rgb(224, 224, 224)",
		width: 156,
		height: 1,
		marginTop: 1,
	},
	labelFourText: {
		backgroundColor: "transparent",
		color: "rgba(28, 27, 27, 0.73)",
		fontSize: 20,
		fontStyle: "normal",
		fontWeight: "normal",
		textAlign: "left",
		alignSelf: "flex-start",
		width: 192,
		height: 24,
		marginTop: 21,
	},
	textFieldSevenTextInput: {
		backgroundColor: "transparent",
		paddingTop: 10,
		color: "black",
		fontSize: 15,
		fontStyle: "normal",
		fontWeight: "normal",
		textAlign: "left",
		flex: 1,
		height: 35,
		marginRight: 14,
		marginTop: 5,
	},
	imageFiveImage: {
		resizeMode: "center",
		backgroundColor: "transparent",
		width: 18,
		height: 18,
		marginLeft: 14,
		marginTop: 17,
	},
	textFieldFiveTextInput: {
		color: "black",
		fontSize: 15,
		fontStyle: "normal",
		fontWeight: "normal",
		textAlign: "left",
		backgroundColor: "transparent",
		paddingTop: 10,
		width: 117,
		height: 35,
		marginRight: 7,
	},
	imageEightImage: {
		backgroundColor: "transparent",
		resizeMode: "center",
		width: 18,
		height: 18,
		marginTop: 17,
	},
	viewSixView: {
		backgroundColor: "rgb(224, 224, 224)",
		width: 155,
		height: 1,
	},
	viewNineView: {
		backgroundColor: "rgb(224, 224, 224)",
		width: 160,
		height: 1,
	},
	labelText: {
		backgroundColor: "transparent",
		color: "rgba(28, 27, 27, 0.73)",
		fontSize: 20,
		fontStyle: "normal",
		fontWeight: "normal",
		textAlign: "left",
		alignSelf: "flex-start",
		width: 192,
		height: 24,
		marginTop: 18,
	},
	textFieldThreeTextInput: {
		backgroundColor: "transparent",
		paddingTop: 10,
		color: "black",
		fontSize: 15,
		fontStyle: "normal",
		fontWeight: "normal",
		textAlign: "left",
		flex: 1,
		height: 35,
		marginRight: 14,
	},
	imageSixImage: {
		resizeMode: "center",
		backgroundColor: "transparent",
		width: 18,
		height: 18,
		marginLeft: 14,
		marginTop: 12,
	},
	textFieldTwoTextInput: {
		backgroundColor: "transparent",
		paddingTop: 10,
		color: "black",
		fontSize: 15,
		fontStyle: "normal",
		fontWeight: "normal",
		textAlign: "left",
		width: 117,
		height: 35,
		marginRight: 7,
	},
	imageNineImage: {
		resizeMode: "center",
		backgroundColor: "transparent",
		width: 18,
		height: 18,
		marginTop: 12,
	},
	viewFourView: {
		backgroundColor: "rgb(224, 224, 224)",
		width: 160,
		height: 1,
		marginTop: 1,
	},
	viewFiveView: {
		backgroundColor: "rgb(224, 224, 224)",
		width: 160,
		height: 1,
	},
	labelTwoText: {
		color: "rgba(28, 27, 27, 0.73)",
		fontSize: 20,
		fontStyle: "normal",
		fontWeight: "normal",
		textAlign: "left",
		backgroundColor: "transparent",
		width: 192,
		height: 24,
	},
	imageTenImage: {
		resizeMode: "center",
		backgroundColor: "transparent",
		width: 18,
		height: 18,
		marginTop: 6,
	},
	labelThreeText: {
		color: "rgba(28, 27, 27, 0.73)",
		fontSize: 20,
		fontStyle: "normal",
		fontWeight: "normal",
		textAlign: "left",
		backgroundColor: "transparent",
		width: 192,
		height: 24,
	},
	imageElevenImage: {
		resizeMode: "center",
		backgroundColor: "transparent",
		width: 18,
		height: 18,
		marginTop: 6,
	},
	buttonButton: {
		backgroundColor: "rgb(224, 224, 224)",
		borderRadius: 20,
		flexDirection: "row",
		alignItems: "center",
		justifyContent: "center",
		padding: 0,
		height: 44,
		marginRight: 3,
		marginTop: 34,
	},
	buttonButtonText: {
		color: "rgba(0, 0, 0, 0.7)",
		fontSize: 20,
		fontStyle: "normal",
		fontWeight: "normal",
		textAlign: "left",
	},
	buttonButtonImage: {
		resizeMode: "contain",
		marginRight: 10,
	},
})

export default styles
