//
//  SignupStyleSheet.js
//  DoubleCritical
//
//  Created by Supernova.
//  Copyright © 2018 S7Works. All rights reserved.
//
 
import { StyleSheet } from "react-native"  

const styles = StyleSheet.create({
	navigationBarItemTitle: {
		color: "white", 
	}, 
	headerLeftContainer: {
		flexDirection: "row",
		marginLeft: 8,
	},
	headerRightContainer: {
		flexDirection: "row",
		marginRight: 8,
	},
	navigationBarItem: {
	},
	signupView: {
		backgroundColor: "white",
		flex: 1,
		alignItems: "center",
	},
	signUpText: {
		color: "rgba(13, 13, 13, 0.68)",
		//fontFamily: "TimesNewRomanPSMT",
		fontSize: 19, 
		fontStyle: "normal",
		fontWeight: "normal",
		textAlign: "center",
		backgroundColor: "transparent",
		width: 171,
		height: 30, 
		marginTop: 30,
	},
	labelText: {
		color: "rgba(0, 0, 0, 0.8)",
		////fontFamily: ".SFNSText",
		fontSize: 19,
		fontStyle: "normal",
		fontWeight: "bold",
		textAlign: "left",
		backgroundColor: "transparent",
		alignSelf: "flex-start",
		width: 281,
		height: 30,
		marginLeft: 20,
		marginTop: 30,
	},
	signUpFieldsView: {
		backgroundColor: "white",
		borderRadius: 2,
		alignSelf: "stretch",
		// height: 111,
		marginLeft: 20,
		marginRight: 20,
		marginTop: 0,
	},
	yourNicknameTextInput: {
		color: "black",
		fontSize: 15,
		fontStyle: "normal",
		fontWeight: "normal",
		textAlign: "left",
		backgroundColor: "transparent",
		padding:0,
		height: 40,
		//marginLeft: 2,
		// marginRight: 30,
		//marginTop: 20,
	},
	separatorView: {
		backgroundColor: "black",
		opacity: 0.1,
		height: 1,
		marginLeft: 2,
		// marginRight: 14,
		marginTop: 0,
	},
	yourSpacemailTextInput: {
		backgroundColor: "transparent",
		padding: 0,
		color: "black",
		fontSize: 15,
		fontStyle: "normal",
		fontWeight: "normal",
		textAlign: "left",
		// height: 20,
		marginLeft: 2,
		// marginRight: 30,
		marginTop: 0,
	},
	separatorTwoView: {
		backgroundColor: "black",
		opacity: 0.1,
		height: 1,
		marginLeft: 2,
		// marginRight: 14,
		marginTop: 0,
	},
	signUpButton: {
		backgroundColor: "rgba(162, 159, 159, 0.54)",
		borderRadius: 30, 
		borderWidth: 1,
		borderColor: "rgba(162, 157, 157, 0.65)",
		borderStyle: "solid",
		flexDirection: "row",
		alignItems: "center",
		justifyContent: "center",
		padding: 0,
		alignSelf: "stretch",
		height: 52,  
		marginLeft: 31,
		marginRight: 29,
		//marginBottom: 280,
		marginTop:30

	},
	signUpSuccessButton: {  
		backgroundColor: "#1D365F",
		borderRadius: 30,
		borderWidth: 1,
		borderColor: "rgba(162, 157, 157, 0.65)",
		borderStyle: "solid",
		flexDirection: "row",
		alignItems: "center",
		justifyContent: "center",
		padding: 0,
		alignSelf: "stretch",
		height: 52,
		marginLeft: 31,
		marginRight: 29,
		//marginBottom: 280,
		marginTop:30

	},
	signUpButtonText: {
		color: "black",
		//fontFamily: "Tahoma",
		fontSize: 15,
		fontStyle: "normal",
		fontWeight: "normal",
		textAlign: "center",
	},
	signUpButtonImage: {
		resizeMode: "contain",
		marginRight: 10, 
	},
	oneTapSignInButton: {
		backgroundColor: "transparent",
		flexDirection: "row",
		alignItems: "center",
		justifyContent: "center",
		padding: 0,
		width: 190,
		height: 31,
		marginBottom: 14,
	},
	oneTapSignInButtonImage: {
		resizeMode: "contain",
		marginRight: 10,
	},
	oneTapSignInButtonText: {
		color: "#585858",
		////fontFamily: ".SFNSText",
		fontSize: 18,
		fontStyle: "normal",
		fontWeight: "normal",
		textAlign: "center",
	},
	buttonButton: {
		backgroundColor: "rgba(3, 14, 75, 0.89)",
		borderRadius: 20,
		flexDirection: "row",
		alignItems: "center",
		justifyContent: "center",
		padding: 0,
		width: 130,
		height: 38,
	},
	buttonButtonText: {
		color: "white",
		////fontFamily: ".SFNSText",
		fontSize: 14,
		fontStyle: "normal",
		fontWeight: "normal",
		textAlign: "left",
	},
	buttonButtonImage: {
		resizeMode: "contain",
		marginRight: 10,
	},
	buttonTwoButtonImage: {
		resizeMode: "contain",
		marginRight: 10,
	},
	buttonTwoButton: {
		backgroundColor: "rgb(12, 139, 202)",
		borderRadius: 20, 
		flexDirection: "row",
		alignItems: "center",
		justifyContent: "center",
		padding: 0,
		width: 130,
		height: 38,
		marginLeft: 33,
	},
	buttonTwoButtonText: {
		color: "white",
		////fontFamily: ".SFNSText",
		fontSize: 14,
		fontStyle: "normal",
		fontWeight: "normal",
		textAlign: "left",
	},
	logInView: {
		backgroundColor: "transparent",
		width: 232,
		height: 18,
		marginBottom: 20,
	},
	alreadyGaveUpYourText: {
		backgroundColor: "transparent",
		color: "white",
		fontSize: 15,
		fontStyle: "normal",
		fontWeight: "normal",
		textAlign: "center",
	},
	logInButton: {
		backgroundColor: "transparent",
		flexDirection: "row",
		alignItems: "center",
		justifyContent: "center",
		padding: 0,
		width: 47,
		height: 18,
	},
	logInButtonText: {
		color: "white",
		fontSize: 15,
		fontStyle: "normal",
		fontWeight: "normal",
		textAlign: "center",
	},
	logInButtonImage: {
		resizeMode: "contain",
		marginRight: 10,
	},
	socialIcons:{
		flex:1,
		alignItems:"center",
		justifyContent:"flex-end",
		margin:20,
	},
})

export default styles
