//
//  UploadGameStyleSheet.js
//  UploadGame
//
//  Created by Supernova.
//  Copyright © 2018 Supernova. All rights reserved.
//

import { StyleSheet } from "react-native"

const styles = StyleSheet.create({
	welcomeView: {
		backgroundColor: "white",
		flex: 1,
		alignItems:'center'
	},
	viewView: {
		backgroundColor: "white",
		position: "absolute",
		left: 0,
		width: 375,
		top: 0,
		height: 667,
	},
	viewThirteenView: {
		backgroundColor: "rgba(58, 28, 140, 0.91)",
		height: 71,
	},
	viewTwoView: {
		backgroundColor: "white",
		alignSelf: "flex-start",
		width: 375,
		height: 596,
	},
	labelText: {
		backgroundColor: "transparent",
		color: "black",
		//fontFamily: "Roboto-Regular",
		fontSize: 15,
		fontWeight:"bold",
		textAlign: "left",
		alignSelf: "flex-start",
	},
	textFieldTwoTextInput: {
		backgroundColor: "transparent",
		padding: 0,
		color: "black",
		//fontFamily: ".SFNSText",
		fontSize: 12,
		fontStyle: "normal",
		fontWeight: "normal",
		textAlign: "left",
		height: 15,
		marginTop: 20,
	},
	viewThreeView: {
		backgroundColor: "white",
		borderWidth: 1,
		borderColor: "rgba(204, 204, 204, 0.86)",
		borderStyle: "solid",
		height: 2,
		marginTop: 5,
	},
	textFieldTextInput: {
		color: "black",
		//fontFamily: ".SFNSText",
		fontSize: 12,
		fontStyle: "normal",
		fontWeight: "normal",
		textAlign: "left",
		backgroundColor: "transparent",
		padding: 0,
		height: 15,
		marginTop: 28,
	},
	viewTwelveView: {
		backgroundColor: "white",
		borderWidth: 1,
		borderColor: "rgba(204, 204, 204, 0.86)",
		borderStyle: "solid",
		height: 2,
		marginTop: 5,
	},
	textFieldTenTextInput: {
		backgroundColor: "transparent",
		padding: 0,
		color: "black",
		//fontFamily: ".SFNSText",
		fontSize: 12,
		fontStyle: "normal",
		fontWeight: "normal",
		textAlign: "left",
		height: 18,
		marginRight: 1,
		marginTop: 28,
	},
	viewElevenView: {
		backgroundColor: "white",
		borderWidth: 1,
		borderColor: "rgba(204, 204, 204, 0.86)",
		borderStyle: "solid",
		height: 2,
		marginTop: 2,
	},
	textFieldNineTextInput: {
		backgroundColor: "transparent",
		padding: 0,
		color: "black",
		//fontFamily: ".SFNSText",
		fontSize: 12,
		fontStyle: "normal",
		fontWeight: "normal",
		textAlign: "left",
		height: 16,
		marginRight: 1,
		marginTop: 28,
	},
	viewTenView: {
		backgroundColor: "white",
		borderWidth: 1,
		borderColor: "rgba(204, 204, 204, 0.86)",
		borderStyle: "solid",
		height: 2,
		marginTop: 4,
	},
	textFieldEightTextInput: {
		backgroundColor: "transparent",
		padding: 0,
		color: "black",
		//fontFamily: ".SFNSText",
		fontSize: 12,
		fontStyle: "normal",
		fontWeight: "normal",
		textAlign: "left",
		height: 19,
		marginTop: 28,
	},
	viewNineView: {
		backgroundColor: "white",
		borderWidth: 1,
		borderColor: "rgba(204, 204, 204, 0.86)",
		borderStyle: "solid",
		height: 2,
		marginTop: 1,
	},
	textFieldSevenTextInput: {
		backgroundColor: "transparent",
		padding: 0,
		color: "black",
		//fontFamily: ".SFNSText",
		fontSize: 12,
		fontStyle: "normal",
		fontWeight: "normal",
		textAlign: "left",
		height: 18,
		marginRight: 1,
		marginTop: 28,
	},
	viewEightView: {
		backgroundColor: "white",
		borderWidth: 1,
		borderColor: "rgba(204, 204, 204, 0.86)",
		borderStyle: "solid",
		height: 2,
		marginTop: 2,
	},
	textFieldSixTextInput: {
		backgroundColor: "transparent",
		padding: 0,
		color: "black",
		//fontFamily: ".SFNSText",
		fontSize: 12,
		fontStyle: "normal",
		fontWeight: "normal",
		textAlign: "left",
		height: 18,
		marginTop: 28,
	},
	viewSevenView: {
		backgroundColor: "white",
		borderWidth: 1,
		borderColor: "rgba(204, 204, 204, 0.86)",
		borderStyle: "solid",
		height: 2,
		marginTop: 2,
	},
	textFieldFiveTextInput: {
		backgroundColor: "transparent",
		padding: 0,
		color: "black",
		//fontFamily: ".SFNSText",
		fontSize: 12,
		fontStyle: "normal",
		fontWeight: "normal",
		textAlign: "left",
		height: 17,
		marginTop: 28,
	},
	viewSixView: {
		backgroundColor: "white",
		borderWidth: 1,
		borderColor: "rgba(204, 204, 204, 0.86)",
		borderStyle: "solid",
		height: 2,
		marginTop: 3,
	},
	textFieldFourTextInput: {
		backgroundColor: "transparent",
		padding: 0,
		color: "black",
		//fontFamily: ".SFNSText",
		fontSize: 12,
		fontStyle: "normal",
		fontWeight: "normal",
		textAlign: "left",
		height: 17,
		marginTop: 28,
	},
	viewFiveView: {
		backgroundColor: "white",
		borderWidth: 1,
		borderColor: "rgba(204, 204, 204, 0.86)",
		borderStyle: "solid",
		height: 2,
		marginTop: 3,
	},
	textFieldThreeTextInput: {
		backgroundColor: "transparent",
		padding: 0,
		color: "black",
		//fontFamily: ".SFNSText",
		fontSize: 12,
		fontStyle: "normal",
		fontWeight: "normal",
		textAlign: "left",
		height: 17,
		marginRight: 1,
		marginTop: 28,
	},
	viewFourView: {
		backgroundColor: "white",
		borderWidth: 1,
		borderColor: "rgba(204, 204, 204, 0.86)",
		borderStyle: "solid",
		height: 2,
		marginTop: 3,
	},
	buttonButton: {
		backgroundColor: "rgba(162, 159, 159, 0.54)",
		borderRadius: 20,
		flexDirection: "row",
		alignItems: "center",
		justifyContent: "center",
		padding: 0,
		alignSelf: "center",
		width: 342,
		height: 52,
		marginTop: 20,
	},
	buttonButtonText: {
		color: "black",
		//fontFamily: "Roboto-Regular",
		fontSize: 14,
		fontStyle: "normal",
		fontWeight: "normal",
		//textAlign: "left",
	},
	buttonButtonImage: {
		resizeMode: "contain",
		marginRight: 10,
	},
	imageImage: {
		backgroundColor: "transparent",
		resizeMode: "center",
		width: 44,
		height: 44,
	},
	labelTwoText: {
		backgroundColor: "transparent",
		color: "white",
		//fontFamily: "Roboto-Regular",
		fontSize: 17,
		fontStyle: "normal",
		fontWeight: "normal",
		textAlign: "left",
		marginLeft: 16,
		marginTop: 13,
	},
	buttonButtonExtends:{
		backgroundColor: "#1D365F",
		borderRadius: 20,
		flexDirection: "row",
		alignItems: "center",
		justifyContent: "center",
		padding: 0,
		alignSelf: "center",
		width: 342,
		height: 52,
		marginTop: 20,
	},
	buttonButtonExtendsText:{
        color: "#fff",
		//fontFamily: "Roboto-Regular",
		fontSize: 14,
		fontStyle: "normal",
		fontWeight: "normal",
	}

})

export default styles
