//
//  FollowingStyleSheet.js
//  DoubleCritical
//
//  Created by Supernova.
//  Copyright © 2018 Supernova. All rights reserved.
//

import { StyleSheet } from "react-native";
import {widthPercentageToDP as wp, heightPercentageToDP as hp} from 'react-native-responsive-screen';

const styles = StyleSheet.create({
	profileView: {
		backgroundColor: "white",
		//flex: 1,
	},
	viewView: {
		backgroundColor: "transparent",
		
		height: 150,
	},
	
	viewTwoViewLinearGradient: {
		height: 100,
	},
	imageTwoImage: {
		backgroundColor: "transparent",
		width: 25,
		height: 25,
	},
	labelText: {
		backgroundColor: "transparent",
		color: "white",
		fontSize: 22,
		fontStyle: "normal",
		fontWeight: "bold",
		textAlign: "left",
		width: 163,
		height: 26,
		marginLeft: 12,
		marginTop: 7,
	},
	imageImage: {
		backgroundColor: "transparent",
		width: 25,
		height: 25,
	},
	viewThreeView: {
		backgroundColor: "black",
		height: 55,
	},
	viewFourView: {
		backgroundColor: "white",
		position: "absolute",
		left: 0,
		right: 0,
		top: 0,
		height: 100,
	},
	segmentedControlSegmentedControl: {
		color: "black",
		fontSize: 15,
		fontStyle: "normal",
		fontWeight: "normal",
		textAlign: "left",
		backgroundColor: "transparent",
		position: "absolute",
		left: 0,
		right: 0,
		top: 0,
		height: 54,
	},
	segmentedControlSegmentedControlTab: {
		borderColor: "rgb(0, 128, 255)",
	},
	segmentedControlSegmentedControlTabText: {
		fontSize: 15,
		fontWeight: "400",
	},
	segmentedControlSegmentedControlActiveTab: {
		backgroundColor: "rgb(0, 128, 255)",
	},
	segmentedControlSegmentedControlActiveTabText: {
		color: "white",
	},
	viewFiveView: {
		backgroundColor: "transparent",
		position: "absolute",
		left: 0,
		right: 0,
		top: 0,
		height: 641,
	},
	viewScrollView: {
		backgroundColor: "white",
		position: "absolute",
		left: 0,
		width: 375,
		top: 0,
		height: 641,
	},
	viewSixView: {
		backgroundColor: "rgb(185, 181, 181)",
		position: "absolute",
		left: 0,
		right: 0,
		top: 200,
		height: 1,
	},
	imageEightImage: {
		backgroundColor: "transparent",
		resizeMode: "center",
		alignSelf: "flex-end",
		width: 29,
		height: 33,
		marginRight: 12,
	},
	viewElevenView: {
		backgroundColor: "white",
		height: 100,
		marginTop: 52,
	},
	viewTenView: {
		backgroundColor: "white",
		alignSelf: "flex-start",
		width: 375,
		height: 99,
		marginTop: 2,
	},
	viewSevenView: {
		backgroundColor: "rgba(137, 134, 134, 0.74)",
		height: 1,
		marginTop: 1,
	},
	viewNineView: {
		backgroundColor: "white",
		alignSelf: "flex-start",
		width: 375,
		height: 100,
	},
	viewEightView: {
		backgroundColor: "rgba(151, 148, 148, 0.58)",
		position: "absolute",
		left: 0,
		right: 0,
		top: 301,
		height: 1,
	},
	imageFourImage: {
		backgroundColor: "rgba(11, 11, 11, 0.71)",
		borderRadius: 30,
		borderWidth: 0,
		borderColor: "black",
		borderStyle: "solid",
		resizeMode: "center",
		width: 60,
		height: 65,
	},
	labelTwoText: {
		color: "rgb(155, 151, 151)",
		fontSize: 15,
		fontStyle: "normal",
		fontWeight: "normal",
		textAlign: "left",
		backgroundColor: "transparent",
		width: 245,
		marginLeft: 16,
		marginTop: 37,
	},
	labelThreeText: {
		color: "black",
		fontSize: 20,
		fontStyle: "normal",
		fontWeight: "normal",
		textAlign: "left",
		backgroundColor: "transparent",
		width: 151,
		height: 24,
		marginTop: 2,
	},
	imageThreeImage: {
		backgroundColor: "transparent",
		resizeMode: "center",
		width: 29,
		height: 33,
	},
	imageSixImage: {
		backgroundColor: "rgba(11, 11, 11, 0.71)",
		borderRadius: 30,
		borderWidth: 0,
		borderColor: "black",
		borderStyle: "solid",
		resizeMode: "center",
		width: 60,
		height: 65,
	},
	labelFourText: {
		color: "rgb(155, 151, 151)",
		fontSize: 15,
		fontStyle: "normal",
		fontWeight: "normal",
		textAlign: "left",
		backgroundColor: "transparent",
		width: 245,
		marginLeft: 16,
		marginTop: 40,
	},
	labelFiveText: {
		color: "black",
		fontSize: 20,
		fontStyle: "normal",
		fontWeight: "normal",
		textAlign: "left",
		backgroundColor: "transparent",
		width: 151,
		height: 24,
		marginTop: 8,
	},
	imageFiveImage: {
		backgroundColor: "transparent",
		resizeMode: "center",
		width: 29,
		height: 33,
	},
	imageSevenImage: {
		backgroundColor: "transparent",
		resizeMode: "center",
		position: "absolute",
		right: 12,
		width: 29,
		top: 116,
		height: 33,
	},
	viewThirteenView: {
		backgroundColor: "white",
		width: 375,
		height: 100,
	},
	viewTwelveView: {
		backgroundColor: "rgb(185, 181, 181)",
		alignSelf: "stretch",
		height: 1,
	},
	imageNineImage: {
		backgroundColor: "rgba(11, 11, 11, 0.71)",
		borderRadius: 30,
		borderWidth: 0,
		borderColor: "black",
		borderStyle: "solid",
		resizeMode: "center",
		width: 60,
		height: 65,
	},
	labelSevenText: {
		backgroundColor: "transparent",
		color: "black",
		fontSize: 20,
		fontStyle: "normal",
		fontWeight: "normal",
		textAlign: "left",
		width: 151,
		height: 24,
	},
	labelSixText: {
		backgroundColor: "transparent",
		color: "rgb(155, 151, 151)",
		fontSize: 15,
		fontStyle: "normal",
		fontWeight: "normal",
		textAlign: "left",
		width: 245,
		marginTop: 8,
	},
	imageElevenImage: {
		backgroundColor: "rgba(11, 11, 11, 0.71)",
		borderRadius: 30,
		borderWidth: 0,
		borderColor: "black",
		borderStyle: "solid",
		resizeMode: "center",
		width: 60,
		height: 65,
	},
	labelEightText: {
		color: "rgb(155, 151, 151)",
		//fontFamily: "Roboto-Regular",
		fontSize: 15,
		fontStyle: "normal",
		fontWeight: "normal",
		textAlign: "left",
		backgroundColor: "transparent",
		width: 244,
		marginLeft: 23,
		marginTop: 37,
	},
	labelNineText: {
		color: "black",
		//fontFamily: "Roboto-Regular",
		fontSize: 20,
		fontStyle: "normal",
		fontWeight: "normal",
		textAlign: "left",
		backgroundColor: "transparent",
		width: 151,
		height: 24,
		marginTop: 8,
	},
	imageTenImage: {
		resizeMode: "center",
		backgroundColor: "transparent",
		width: 29,
		height: 33,
	},


	viewTwoView: {
		backgroundColor: "transparent",
		height: 605,
	},
	bodyView: {
		backgroundColor: "white",
		position: "absolute",
		left: 0,
		right: 0,
		top: 0,
		height: 605,
	},
	viewFourView: {
		backgroundColor: "transparent",
		position: "absolute",
		left: 0,
		right: 0,
		top: 4,
		height: 455,
	},
	scanninginfoView: {
		backgroundColor: "white",
		position: "absolute",
		left: 0,
		width: 375,
		top: 0,
		height: 548,
	},
	viewTweleveView: {
		backgroundColor: "transparent",
		height: 72,
		marginLeft: 4,
		flexDirection:'row'
	},
	game1View: {
		backgroundColor: "white",
		position: "absolute",
		left: 0,
		width: 375,
		top: 0,
		height: 78,
	},
	imageTweleveImage: {
		backgroundColor: "transparent",
		height: 50,
		width:50,
		borderRadius:25,
		//marginTop:3,
		//flex:1
	},
	labelTenText: {
		backgroundColor: "transparent",
		color: "rgba(0, 0, 0, 0.8)",
		//fontFamily: "Roboto-Regular",
		fontSize: 15,
		fontStyle: "normal",
		fontWeight: "bold",
		alignSelf:"flex-start",
		width: 500,
		height: 30,
		//marginTop:5,
	},
	labelElevenText: {
		color: "rgba(0, 0, 0, 0.41)",
		//fontFamily: "Roboto-Regular",
		fontSize: 12,
		fontStyle: "normal",
		fontWeight: "normal",
		alignSelf:"flex-start",
		backgroundColor: "transparent",

		//marginTop:3,
	},
	imageTwelveImage: {
		backgroundColor: "transparent",
		//resizeMode: "center",
		// flex: 1,
		// height: 32,
		//marginLeft: 30,
		marginTop:18,
	},
	seperator2View: {
		backgroundColor: "rgb(192, 192, 192)",
		height: 1,
		marginLeft: 4,
		marginTop: 5,
	},
	seperator3View: {
		backgroundColor: "rgb(192, 192, 192)",
		height: 1,
		marginLeft: 4,
		marginTop: 8,
	},
	following_View:{
		position: "absolute",
		left: 13,
		right: 16,
		top: 10,
		height: 59,
		flexDirection: "row",
		alignItems: "flex-start",
	},
	following_content:{
		width: 234,
		height: 40,
		marginLeft: 18,
		marginTop: 2,
		alignItems: "flex-start",
	},
	follower_view:{
		position: "absolute",
		left: 13,
		right: 16,
		top: 10,
		height: 59,
		flexDirection: "row",
		alignItems: "flex-start",
	},
	follower_content:{
		width: 234,
		height: 40,
		marginLeft: 18,
		//marginTop: 2,
		alignItems: "flex-start",
	},
	following_scroll:{
		position: "absolute",
		left: 0,
		right: 0,
		top: 0,
		height: 150,
	}
})

export default styles
